#include <iostream>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
using namespace std;

int main(){
  int lim = 4000000;
  int first = 1;
  int second = 2;
  int res_sum = 0;
  while (second <= lim) {
    // Keep running sum
    if (second % 2 == 0) {
      res_sum += second;
    }
    int new_ele = first + second;
    first = second;
    second = new_ele;
  }
  cout << "Sum of even values is: " << res_sum << endl;
  return 0;
}
